### ISSUE TITLE
Same waifu?

### ISSUE THREAD

**Issue by RaitaroH** [limingwu8/DCGAN#1]
So here is a scenario:
1. feed the network only files from the same artist (thus same artstyle)
2. after it understands the artstyle you feed it only pictures with one character drawn by that artist
3. have pictures of the same character but in different poses

**Comment by limingwu8** [comment]
The character in these images are same because they use the same initial noise.

**Comment by RaitaroH** [comment]
@limingwu8 Yeah... I know. And my scenario was entirely different but fuck it.
